name: Docker Build Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  DOCKER_USERNAME: flytoogoal
  DOCKER_PASSWORD: flytoogoal@gmail.com
  PRODUCT_REPO_NAME: DEPLOYER

jobs:
  create-user-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Work Dir
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $PRODUCT_REPO_NAME
      - name: Docker login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build user service docker image
        run: docker build . --file Dockerfile -t "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"
      - name: Push user service docker image
        run: docker push "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:latest"

 
# name: remote ssh command
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ main ]
# jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@v0.1.10
#       with:
#         host: 164.92.94.139
#         username: root
#         password: dc^%876HA
#         port: 22
#         script: whoami